### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-zenvideo-ndirouter#1]
Either this module is not working, Or I am doing something wrong. I need to use this in a project, but no go.
There is no documentation on how to use it or examples or presets.
Nothing populates the input/output fields and no matter what I try to enter it does not work.
I am connected and the "remote app" works.

[https://www.ndistuff.uk/zen-ndi-router-remote-panel/](https://www.ndistuff.uk/zen-ndi-router-remote-panel/)

Please help?
Thanks

**Comment by stevespaw** [comment]
Also Feedback would be nice too :-)

**Comment by stevespaw** [comment]
OK after messing with it for an hour, I tried just numbers 1 and 2. = input "B 1" to output B bus.
This works......
Now if we had feedback :-)

**Comment by josephdadams** [comment]
https://www.ndistuff.uk/downloads/ZEN_NDI_Router_protocol3.pdf

Here is a link to the router protocol, for anyone who wants to amend this module to add the feedbacks.
