### ISSUE TITLE
Module registration failed Error with latest stable (3.3.0)

### ISSUE THREAD

**Issue by am0** [bitfocus/companion-module-zenvideo-ndirouter#13]
Hi there,

Getting this error with the latest stable version, after not changing anything else with the system

`error,"Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\bundled-modules\zenvideo-ndirouter\main.js:1:428377)
    at C:\Program Files\Companion\resources\bundled-modules\zenvideo-ndirouter\main.js:1:421173"`

Full log attached if useful, would appreciate any insights! Thanks!

[module-log-22_05_2024-14 19 59.csv](https://github.com/bitfocus/companion-module-zenvideo-ndirouter/files/15404077/module-log-22_05_2024-14.19.59.csv)

**Comment by istnv** [comment]
Which version of NDI Router are you using?

**Comment by am0** [comment]
> Which version of NDI Router are you using?

Latest 1.5.2.40, downgrading back to previous Companion version fixes it though. Happy to run further tests etc

**Comment by istnv** [comment]
My test router did not have any missing inputs.
The name/network query returns a different response format.
