### ISSUE TITLE
Unable to recall a preset which uses a higher number than the set number of outputs

### ISSUE THREAD

**Issue by jessehazen** [bitfocus/companion-module-zenvideo-ndirouter#16]
It is not possible to switch to a preset number that is higher than the total number of outputs configured in Zen NDI Router/Switcher.

When doing so, the following error appears on the "connection status" for NDIRouter:

```
Bad Configuration
Bad preset number on 2/3/3
```

To reproduce:

1. Start ZEN NDI Router/Switcher
2. Create router with less outputs than inputs. In my case, I created a router with 8 inputs, and 3 outputs.
3. Set up inputs, outputs, and presets as needed.
4. In Companion, create a button to recall a preset number that is higher than the total number of outputs. In my case, I created a button to switch to recall preset 4.
5. Attempt to recall the preset
6. Observe the error in Connections > NDIRouter > Status
7. Note also, that in my case, recalling presets 1-3 will work as expected.

Other info:
Companion Version: 3.3.1
NDIRouter plugin version: 2.4.1
NDIRouter version:  Unknown (Not sure how to tell? Pretty sure it is the latest available)

**Comment by istnv** [comment]
The module is limiting presets to the number of outputs, not the number of inputs. I'll try to fix this in the next day or so.
FYI: Right click on the Title bar. You will find 'About...' there.

**Comment by jessehazen** [comment]
@istnv Thanks for the quick turnaround!
