### ISSUE TITLE
Enable variable support

### ISSUE THREAD

**Issue by guimacjr** [bitfocus/companion-module-zenvideo-ndirouter#2]
Is it possible to add variable support for the routing? This way we don't need to create a button for each possible routing.

**Comment by josephdadams** [comment]
You mean like where you can type in a custom variable and it will parse it and use that value?

**Comment by guimacjr** [comment]
Yes, by using variables I can use it more like an smart videohub, with around 24 buttons I can control all routes.

My idea was:
Numbered buttons between 1 and 20. When you press the button it sets a $Select to it's number.
2 buttons, one for in and one for out. When you press it, it will move the variable $Select to $Out or $In
One button to confirm, this button run the command to route $In to $Out, but, since it wont accept variables, I can't do this way.
