### ISSUE TITLE
Variable and Feedback?

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-zenvideo-ndirouter#3]
Is this module actively developed?  Just wondering if there were plans to add variables and feedbacks?  Looks like the documentation is attached on the other issue.  I really need to learn code...:)  Thanks!

**Comment by obcocav** [comment]
What would it take $$ to get this module updated for feedback, variables(inputs too), and V3?  Don’t have a lot of budget as it’s for my church but want to see what’s possible.    Thanks to anyone able and interested!

I really need to learn to code….:/

**Comment by istnv** [comment]
Hoping to work on this this week.
